# Generated by Django 4.1 on 2022-11-22 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="create_date",),
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 22, 16, 0, 28, 134906, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 22, 16, 0, 28, 134906, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
