# Generated by Django 4.1 on 2022-11-22 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_create_date_post_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comment", name="text", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
