# Generated by Django 4.1 on 2022-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_created_date_alter_comment_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
